name: build konga
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    build:
      name: Docker image
      runs-on: [ self-hosted, non-api ]
      steps:
        - uses: actions/checkout@v3
        - name: Login to Harbor
          uses: docker/login-action@v1
          with:
            registry: c.rzp.io
            username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
            password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            platforms: linux/arm64,linux/amd64
            push: true
            tags: c.rzp.io/${{ github.repository }}:${{ github.sha }}